import type { ClientRecord, SessionRecord } from "@/lib/domain";

export const demoStandaloneSessions: SessionRecord[] = [
  {
    id: "session-marcus-0328-orphan",
    clientId: "client-marcus-reed",
    caseId: "case-marcus-therapy",
    serviceId: "service-marcus-90837",
    authorizationId: null,
    employeeId: null,
    clinicianName: "Danielle Brooks",
    clinicianTitle: "LCSW",
    scheduledStart: "2026-03-28T11:00:00-04:00",
    scheduledEnd: "2026-03-28T12:00:00-04:00",
    location: "Telehealth",
    sessionType: "Individual therapy",
    attendanceStatus: "SCHEDULED",
    unitsRendered: 1,
    noteStatus: "DRAFT",
    billingStatus: "READY",
    documentationDueAt: "2026-03-29T12:00:00-04:00",
    progressNotes: [],
  },
];

export const demoClients: ClientRecord[] = [
  {
    id: "client-elena-martinez",
    externalId: "CED-100214",
    firstName: "Elena",
    lastName: "Martinez",
    preferredName: "Elena",
    dateOfBirth: "2017-08-14",
    email: "martinez.family@example.com",
    phone: "(571) 555-0174",
    city: "Ashburn",
    state: "VA",
    timezone: "America/New_York",
    status: "ACTIVE",
    riskLevel: "MODERATE",
    primaryDiagnosisCode: "F84.0",
    payerSegment: "Medicaid Managed Care",
    referralSource: "Pediatric neurology",
    cases: [
      {
        id: "case-elena-aba",
        caseNumber: "C-24017",
        caseType: "ABA",
        programName: "Home and community ABA",
        payerName: "Anthem HealthKeepers Plus",
        clinicalLead: "Sofia Nguyen, BCBA",
        renderingProvider: "Synetra Behavioral Health",
        location: "Northern Virginia hybrid",
        status: "ACTIVE",
        startDate: "2026-01-08",
        acuityLevel: "High support with caregiver coaching",
        carePlanSummary:
          "Reduce elopement, increase transitions tolerance, and expand caregiver carryover during afternoon routines.",
        services: [
          {
            id: "service-elena-97153",
            serviceCode: "97153",
            title: "Adaptive behavior treatment by protocol",
            discipline: "ABA",
            unitType: "UNITS",
            defaultUnitsPerSession: 16,
            defaultRateCents: 5800,
            frequency: "4x weekly after school",
            status: "ACTIVE",
            isPrimary: true,
            authorizations: [
              {
                id: "auth-elena-97153-q1",
                authorizationNumber: "AVA-448201",
                payerName: "Anthem HealthKeepers Plus",
                approvedUnits: 624,
                usedUnits: 412,
                remainingUnits: 212,
                unitType: "UNITS",
                startDate: "2026-01-01",
                endDate: "2026-06-30",
                status: "ACTIVE",
                utilizationThreshold: 85,
                notes:
                  "Family requested Saturday make-up options for missed school-based appointments.",
                sessions: [
                  {
                    id: "session-elena-0325",
                    scheduledStart: "2026-03-25T15:30:00-04:00",
                    scheduledEnd: "2026-03-25T19:30:00-04:00",
                    clinicianName: "Mia Thompson",
                    clinicianTitle: "RBT",
                    location: "In-home",
                    sessionType: "Direct therapy",
                    attendanceStatus: "COMPLETED",
                    unitsRendered: 16,
                    noteStatus: "SIGNED",
                    billingStatus: "SUBMITTED",
                    documentationDueAt: "2026-03-26T12:00:00-04:00",
                    progressNotes: [
                      {
                        id: "note-elena-0325",
                        authorName: "Mia Thompson",
                        status: "SIGNED",
                        submittedAt: "2026-03-25T20:12:00-04:00",
                        signedAt: "2026-03-26T09:05:00-04:00",
                        subjective:
                          "Caregiver reported improved bedtime routine and fewer refusals during arrival transition.",
                        objective:
                          "Elena completed 14 independent transitions with 2 gestural prompts and tolerated 3 new play demands.",
                        assessment:
                          "Protocol remains effective; visual countdown continues to reduce escalation before cleanup demands.",
                        plan:
                          "Advance peer-join goal and add school-prep rehearsal before Thursday session.",
                        incidentReported: false,
                        billingRecords: [
                          {
                            id: "billing-elena-0325",
                            claimNumber: "CLM-240325-001",
                            cptCode: "97153",
                            unitsBilled: 16,
                            amountCents: 92800,
                            status: "SUBMITTED",
                            submittedAt: "2026-03-26T10:00:00-04:00",
                          },
                        ],
                        complianceItems: [],
                      },
                    ],
                  },
                  {
                    id: "session-elena-0327",
                    scheduledStart: "2026-03-27T15:30:00-04:00",
                    scheduledEnd: "2026-03-27T19:30:00-04:00",
                    clinicianName: "Mia Thompson",
                    clinicianTitle: "RBT",
                    location: "In-home",
                    sessionType: "Direct therapy",
                    attendanceStatus: "SCHEDULED",
                    unitsRendered: 16,
                    noteStatus: "DRAFT",
                    billingStatus: "READY",
                    documentationDueAt: "2026-03-28T12:00:00-04:00",
                    progressNotes: [
                      {
                        id: "note-elena-0327",
                        authorName: "Mia Thompson",
                        status: "DRAFT",
                        subjective:
                          "Draft placeholder created from scheduling template for next direct session.",
                        objective:
                          "Awaiting rendered session data.",
                        assessment:
                          "Session not yet delivered.",
                        plan:
                          "Complete note after treatment occurs.",
                        incidentReported: false,
                        billingRecords: [],
                        complianceItems: [],
                      },
                    ],
                  },
                ],
              },
              {
                id: "auth-elena-97153-q3",
                authorizationNumber: "AVA-448201-R2",
                payerName: "Anthem HealthKeepers Plus",
                approvedUnits: 624,
                usedUnits: 0,
                remainingUnits: 624,
                unitType: "UNITS",
                startDate: "2026-07-01",
                endDate: "2026-12-31",
                status: "REQUESTED",
                utilizationThreshold: 85,
                notes:
                  "Renewal packet is ready pending updated Vineland and parent goals.",
                sessions: [],
              },
            ],
          },
          {
            id: "service-elena-97155",
            serviceCode: "97155",
            title: "Protocol modification and caregiver training",
            discipline: "ABA",
            unitType: "UNITS",
            defaultUnitsPerSession: 4,
            defaultRateCents: 7600,
            frequency: "1x weekly BCBA",
            status: "ACTIVE",
            isPrimary: false,
            authorizations: [
              {
                id: "auth-elena-97155-q1",
                authorizationNumber: "AVA-448202",
                payerName: "Anthem HealthKeepers Plus",
                approvedUnits: 48,
                usedUnits: 39,
                remainingUnits: 9,
                unitType: "UNITS",
                startDate: "2026-01-01",
                endDate: "2026-04-15",
                status: "EXPIRING",
                utilizationThreshold: 80,
                notes:
                  "Review supervision frequency before April utilization crosses 90%.",
                sessions: [
                  {
                    id: "session-elena-0324-bcba",
                    scheduledStart: "2026-03-24T17:00:00-04:00",
                    scheduledEnd: "2026-03-24T18:00:00-04:00",
                    clinicianName: "Sofia Nguyen",
                    clinicianTitle: "BCBA",
                    location: "Telehealth caregiver coaching",
                    sessionType: "Protocol modification",
                    attendanceStatus: "COMPLETED",
                    unitsRendered: 4,
                    noteStatus: "PENDING_SIGNATURE",
                    billingStatus: "READY",
                    documentationDueAt: "2026-03-25T12:00:00-04:00",
                    progressNotes: [
                      {
                        id: "note-elena-0324-bcba",
                        authorName: "Sofia Nguyen",
                        status: "PENDING_SIGNATURE",
                        submittedAt: "2026-03-24T18:35:00-04:00",
                        subjective:
                          "Parent requested additional support for sibling interruptions during mealtime intervention blocks.",
                        objective:
                          "BCBA updated prompting hierarchy and modeled parent coaching routine with live feedback.",
                        assessment:
                          "Plan revision is clinically indicated due to increased contextual interference in the home setting.",
                        plan:
                          "Finalize updated protocol and send parent handout before Friday direct session.",
                        incidentReported: false,
                        billingRecords: [
                          {
                            id: "billing-elena-0324-bcba",
                            claimNumber: "CLM-240324-006",
                            cptCode: "97155",
                            unitsBilled: 4,
                            amountCents: 30400,
                            status: "READY",
                          },
                        ],
                        complianceItems: [
                          {
                            id: "compliance-elena-signature",
                            title: "Supervisor signature due",
                            description:
                              "BCBA note was submitted but supervising signature has not been completed within the standard 24-hour window.",
                            severity: "MEDIUM",
                            status: "OPEN",
                            dueDate: "2026-03-25T18:35:00-04:00",
                            owner: "Clinical QA",
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "client-marcus-reed",
    externalId: "CED-100441",
    firstName: "Marcus",
    lastName: "Reed",
    preferredName: "Marcus",
    dateOfBirth: "2004-01-09",
    email: "marcus.reed@example.com",
    phone: "(804) 555-0188",
    city: "Richmond",
    state: "VA",
    timezone: "America/New_York",
    status: "ACTIVE",
    riskLevel: "HIGH",
    primaryDiagnosisCode: "F43.10",
    payerSegment: "Commercial PPO",
    referralSource: "Primary care behavioral health",
    cases: [
      {
        id: "case-marcus-therapy",
        caseNumber: "C-24092",
        caseType: "MENTAL_HEALTH",
        programName: "Adult outpatient trauma therapy",
        payerName: "Aetna PPO",
        clinicalLead: "Danielle Brooks, LCSW",
        renderingProvider: "Synetra Counseling",
        location: "Telehealth statewide",
        status: "ACTIVE",
        startDate: "2025-12-11",
        acuityLevel: "Moderate with relapse prevention",
        carePlanSummary:
          "Stabilize sleep, reduce panic reactivity, and support work re-entry with weekly psychotherapy and monthly med management.",
        services: [
          {
            id: "service-marcus-90837",
            serviceCode: "90837",
            title: "Psychotherapy, 60 minutes",
            discipline: "THERAPY",
            unitType: "VISITS",
            defaultUnitsPerSession: 1,
            defaultRateCents: 18500,
            frequency: "Weekly",
            status: "ACTIVE",
            isPrimary: true,
            authorizations: [
              {
                id: "auth-marcus-therapy",
                authorizationNumber: "AET-90217",
                payerName: "Aetna PPO",
                approvedUnits: 24,
                usedUnits: 17,
                remainingUnits: 7,
                unitType: "VISITS",
                startDate: "2026-01-01",
                endDate: "2026-06-30",
                status: "ACTIVE",
                utilizationThreshold: 75,
                sessions: [
                  {
                    id: "session-marcus-0323",
                    scheduledStart: "2026-03-23T18:00:00-04:00",
                    scheduledEnd: "2026-03-23T19:00:00-04:00",
                    clinicianName: "Danielle Brooks",
                    clinicianTitle: "LCSW",
                    location: "Telehealth",
                    sessionType: "Individual therapy",
                    attendanceStatus: "COMPLETED",
                    unitsRendered: 1,
                    noteStatus: "SIGNED",
                    billingStatus: "PAID",
                    documentationDueAt: "2026-03-24T12:00:00-04:00",
                    progressNotes: [
                      {
                        id: "note-marcus-0323",
                        authorName: "Danielle Brooks",
                        status: "SIGNED",
                        submittedAt: "2026-03-23T19:18:00-04:00",
                        signedAt: "2026-03-23T19:24:00-04:00",
                        subjective:
                          "Marcus reported two consecutive nights of improved sleep and lower daytime hypervigilance.",
                        objective:
                          "Completed exposure hierarchy review and practiced grounding sequence without prompting.",
                        assessment:
                          "Clinical progress is steady; patient demonstrates improved tolerance for trauma processing work.",
                        plan:
                          "Continue weekly therapy and track return-to-work anxiety rating before next session.",
                        incidentReported: false,
                        billingRecords: [
                          {
                            id: "billing-marcus-0323",
                            claimNumber: "CLM-240323-011",
                            cptCode: "90837",
                            unitsBilled: 1,
                            amountCents: 18500,
                            status: "PAID",
                            submittedAt: "2026-03-23T19:30:00-04:00",
                            paidAt: "2026-03-24T15:00:00-04:00",
                          },
                        ],
                        complianceItems: [],
                      },
                    ],
                  },
                  {
                    id: "session-marcus-0330",
                    scheduledStart: "2026-03-30T18:00:00-04:00",
                    scheduledEnd: "2026-03-30T19:00:00-04:00",
                    clinicianName: "Danielle Brooks",
                    clinicianTitle: "LCSW",
                    location: "Telehealth",
                    sessionType: "Individual therapy",
                    attendanceStatus: "SCHEDULED",
                    unitsRendered: 1,
                    noteStatus: "DRAFT",
                    billingStatus: "READY",
                    documentationDueAt: "2026-03-31T12:00:00-04:00",
                    progressNotes: [
                      {
                        id: "note-marcus-0330",
                        authorName: "Danielle Brooks",
                        status: "DRAFT",
                        subjective: "Pre-chart started for upcoming visit.",
                        objective: "Awaiting rendered visit.",
                        assessment: "No clinical content captured yet.",
                        plan: "Complete after session.",
                        incidentReported: false,
                        billingRecords: [],
                        complianceItems: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            id: "service-marcus-99214",
            serviceCode: "99214",
            title: "Medication management follow-up",
            discipline: "PSYCHIATRY",
            unitType: "VISITS",
            defaultUnitsPerSession: 1,
            defaultRateCents: 21000,
            frequency: "Monthly",
            status: "ACTIVE",
            isPrimary: false,
            authorizations: [
              {
                id: "auth-marcus-med",
                authorizationNumber: "AET-92114",
                payerName: "Aetna PPO",
                approvedUnits: 12,
                usedUnits: 4,
                remainingUnits: 8,
                unitType: "VISITS",
                startDate: "2026-01-01",
                endDate: "2026-12-31",
                status: "ACTIVE",
                utilizationThreshold: 90,
                sessions: [
                  {
                    id: "session-marcus-0318-med",
                    scheduledStart: "2026-03-18T12:00:00-04:00",
                    scheduledEnd: "2026-03-18T12:30:00-04:00",
                    clinicianName: "Alicia Monroe",
                    clinicianTitle: "PMHNP",
                    location: "Telehealth",
                    sessionType: "Psychiatry follow-up",
                    attendanceStatus: "COMPLETED",
                    unitsRendered: 1,
                    noteStatus: "SIGNED",
                    billingStatus: "HOLD",
                    documentationDueAt: "2026-03-19T12:00:00-04:00",
                    progressNotes: [
                      {
                        id: "note-marcus-0318-med",
                        authorName: "Alicia Monroe",
                        status: "SIGNED",
                        submittedAt: "2026-03-18T12:42:00-04:00",
                        signedAt: "2026-03-18T13:05:00-04:00",
                        subjective:
                          "Client denied medication side effects and endorsed lower nighttime activation.",
                        objective:
                          "Reviewed medication adherence, PHQ-9 trend, and safety plan acknowledgement.",
                        assessment:
                          "Symptoms are improving; current regimen remains appropriate with close monitoring.",
                        plan:
                          "Continue current dose and reassess in four weeks.",
                        incidentReported: false,
                        billingRecords: [
                          {
                            id: "billing-marcus-0318-med",
                            claimNumber: "CLM-240318-019",
                            cptCode: "99214",
                            unitsBilled: 1,
                            amountCents: 21000,
                            status: "HOLD",
                            denialReason: "Member coordination of benefits still pending.",
                          },
                        ],
                        complianceItems: [
                          {
                            id: "compliance-marcus-cob",
                            title: "Payer coordination hold",
                            description:
                              "Billing is on hold until updated coordination-of-benefits documentation is attached to the claim packet.",
                            severity: "MEDIUM",
                            status: "OPEN",
                            dueDate: "2026-03-26T17:00:00-04:00",
                            owner: "Revenue Ops",
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "client-naomi-chen",
    externalId: "CED-100593",
    firstName: "Naomi",
    lastName: "Chen",
    preferredName: "Naomi",
    dateOfBirth: "2013-11-03",
    email: "chen.family@example.com",
    phone: "(703) 555-0161",
    city: "Fairfax",
    state: "VA",
    timezone: "America/New_York",
    status: "ACTIVE",
    riskLevel: "LOW",
    primaryDiagnosisCode: "F90.2",
    payerSegment: "Medicaid Managed Care",
    referralSource: "School social work team",
    cases: [
      {
        id: "case-naomi-school",
        caseNumber: "C-24103",
        caseType: "SCHOOL_SUPPORT",
        programName: "School-based behavioral support",
        payerName: "UnitedHealthcare Community Plan",
        clinicalLead: "Rebekah Owens, LPC",
        renderingProvider: "Synetra School Services",
        location: "Fairfax County schools",
        status: "ACTIVE",
        startDate: "2026-02-03",
        acuityLevel: "School coordination with classroom generalization",
        carePlanSummary:
          "Improve class transition independence, reduce peer conflict escalations, and align home-school reinforcement strategies.",
        services: [
          {
            id: "service-naomi-h2019",
            serviceCode: "H2019",
            title: "Therapeutic behavioral services",
            discipline: "SKILLS_TRAINING",
            unitType: "HOURS",
            defaultUnitsPerSession: 2,
            defaultRateCents: 12800,
            frequency: "3x weekly in school",
            status: "ACTIVE",
            isPrimary: true,
            authorizations: [
              {
                id: "auth-naomi-h2019",
                authorizationNumber: "UHC-31082",
                payerName: "UnitedHealthcare Community Plan",
                approvedUnits: 120,
                usedUnits: 103,
                remainingUnits: 17,
                unitType: "HOURS",
                startDate: "2026-02-01",
                endDate: "2026-04-30",
                status: "EXPIRING",
                utilizationThreshold: 80,
                notes:
                  "Plan for continuity request now that utilization has exceeded 85% with six weeks remaining in the auth span.",
                sessions: [
                  {
                    id: "session-naomi-0326",
                    scheduledStart: "2026-03-26T10:00:00-04:00",
                    scheduledEnd: "2026-03-26T12:00:00-04:00",
                    clinicianName: "Jocelyn Grant",
                    clinicianTitle: "QMHP",
                    location: "Elementary school campus",
                    sessionType: "School-based skills training",
                    attendanceStatus: "SCHEDULED",
                    unitsRendered: 2,
                    noteStatus: "DRAFT",
                    billingStatus: "READY",
                    documentationDueAt: "2026-03-27T12:00:00-04:00",
                    progressNotes: [
                      {
                        id: "note-naomi-0326",
                        authorName: "Jocelyn Grant",
                        status: "DRAFT",
                        subjective:
                          "Session template prepared for school-based support block.",
                        objective: "Awaiting service delivery.",
                        assessment: "No session delivered yet.",
                        plan: "Complete after session.",
                        incidentReported: false,
                        billingRecords: [],
                        complianceItems: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            id: "service-naomi-t1017",
            serviceCode: "T1017",
            title: "Targeted case management",
            discipline: "CARE_COORDINATION",
            unitType: "HOURS",
            defaultUnitsPerSession: 1,
            defaultRateCents: 9600,
            frequency: "2x monthly family-school coordination",
            status: "ACTIVE",
            isPrimary: false,
            authorizations: [
              {
                id: "auth-naomi-t1017",
                authorizationNumber: "UHC-31082-CM",
                payerName: "UnitedHealthcare Community Plan",
                approvedUnits: 24,
                usedUnits: 18,
                remainingUnits: 6,
                unitType: "HOURS",
                startDate: "2026-02-01",
                endDate: "2026-04-30",
                status: "ACTIVE",
                utilizationThreshold: 75,
                sessions: [
                  {
                    id: "session-naomi-0321-cm",
                    scheduledStart: "2026-03-21T16:00:00-04:00",
                    scheduledEnd: "2026-03-21T17:00:00-04:00",
                    clinicianName: "Rebekah Owens",
                    clinicianTitle: "LPC",
                    location: "Family teleconference",
                    sessionType: "Care coordination",
                    attendanceStatus: "COMPLETED",
                    unitsRendered: 1,
                    noteStatus: "SIGNED",
                    billingStatus: "SUBMITTED",
                    documentationDueAt: "2026-03-22T12:00:00-04:00",
                    progressNotes: [
                      {
                        id: "note-naomi-0321-cm",
                        authorName: "Rebekah Owens",
                        status: "SIGNED",
                        submittedAt: "2026-03-21T17:22:00-04:00",
                        signedAt: "2026-03-21T18:04:00-04:00",
                        subjective:
                          "Family and school counselor aligned on reward menu revisions after recent cafeteria escalation.",
                        objective:
                          "Documented classroom accommodations update and parent communication workflow.",
                        assessment:
                          "Care coordination remains necessary to support consistent behavior response across settings.",
                        plan:
                          "Send revised reinforcement menu and re-check with teacher next Tuesday.",
                        incidentReported: false,
                        billingRecords: [
                          {
                            id: "billing-naomi-0321-cm",
                            claimNumber: "CLM-240321-004",
                            cptCode: "T1017",
                            unitsBilled: 1,
                            amountCents: 9600,
                            status: "SUBMITTED",
                            submittedAt: "2026-03-22T09:00:00-04:00",
                          },
                        ],
                        complianceItems: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "client-jordan-ellis",
    externalId: "CED-100702",
    firstName: "Jordan",
    lastName: "Ellis",
    preferredName: "Jordan",
    dateOfBirth: "2010-05-27",
    email: "ellis.family@example.com",
    phone: "(757) 555-0116",
    city: "Chesapeake",
    state: "VA",
    timezone: "America/New_York",
    status: "HOLD",
    riskLevel: "MODERATE",
    primaryDiagnosisCode: "F91.3",
    payerSegment: "Medicaid Managed Care",
    referralSource: "Community services board",
    cases: [
      {
        id: "case-jordan-care",
        caseNumber: "C-24066",
        caseType: "CARE_COORDINATION",
        programName: "Youth wraparound coordination",
        payerName: "Molina Complete Care",
        clinicalLead: "Ian Foster, QMHP",
        renderingProvider: "Synetra Community Services",
        location: "South Hampton Roads",
        status: "ON_HOLD",
        startDate: "2025-11-04",
        acuityLevel: "Family stabilization bridge",
        carePlanSummary:
          "Coordinate school attendance supports, psychiatry follow-up, and respite access while family transitions between service systems.",
        services: [
          {
            id: "service-jordan-t1017",
            serviceCode: "T1017",
            title: "Targeted case management",
            discipline: "CARE_COORDINATION",
            unitType: "HOURS",
            defaultUnitsPerSession: 1,
            defaultRateCents: 9900,
            frequency: "Weekly during active phase",
            status: "PAUSED",
            isPrimary: true,
            authorizations: [
              {
                id: "auth-jordan-t1017",
                authorizationNumber: "MOL-76103",
                payerName: "Molina Complete Care",
                approvedUnits: 40,
                usedUnits: 34,
                remainingUnits: 6,
                unitType: "HOURS",
                startDate: "2026-01-01",
                endDate: "2026-03-31",
                status: "EXPIRING",
                utilizationThreshold: 80,
                notes:
                  "Case is paused while family decides whether to transition to intensive in-home services.",
                sessions: [
                  {
                    id: "session-jordan-0317",
                    scheduledStart: "2026-03-17T16:00:00-04:00",
                    scheduledEnd: "2026-03-17T17:00:00-04:00",
                    clinicianName: "Ian Foster",
                    clinicianTitle: "QMHP",
                    location: "Community visit",
                    sessionType: "Family systems coordination",
                    attendanceStatus: "COMPLETED",
                    unitsRendered: 1,
                    noteStatus: "SIGNED",
                    billingStatus: "DENIED",
                    documentationDueAt: "2026-03-18T12:00:00-04:00",
                    progressNotes: [
                      {
                        id: "note-jordan-0317",
                        authorName: "Ian Foster",
                        status: "SIGNED",
                        submittedAt: "2026-03-17T17:20:00-04:00",
                        signedAt: "2026-03-17T18:00:00-04:00",
                        subjective:
                          "Caregiver requested service pause while evaluating intensive in-home referral options.",
                        objective:
                          "Confirmed school attendance plan and documented referral handoff to CSB coordinator.",
                        assessment:
                          "Short-term coordination remains appropriate, but payer may deny additional units without updated medical necessity.",
                        plan:
                          "Hold scheduling, pursue payer reconsideration, and follow up within seven days.",
                        incidentReported: false,
                        billingRecords: [
                          {
                            id: "billing-jordan-0317",
                            claimNumber: "CLM-240317-022",
                            cptCode: "T1017",
                            unitsBilled: 1,
                            amountCents: 9900,
                            status: "DENIED",
                            denialReason:
                              "Authorization span ended before documentation packet reached payer portal.",
                          },
                        ],
                        complianceItems: [
                          {
                            id: "compliance-jordan-auth-gap",
                            title: "Authorization coverage gap",
                            description:
                              "Rendered session requires reconsideration because the authorization packet was not extended before the payer deadline.",
                            severity: "HIGH",
                            status: "OPEN",
                            dueDate: "2026-03-25T17:00:00-04:00",
                            owner: "Utilization Management",
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "client-priya-patel",
    externalId: "CED-100118",
    firstName: "Priya",
    lastName: "Patel",
    preferredName: "Priya",
    dateOfBirth: "2015-02-19",
    email: "patel.family@example.com",
    phone: "(703) 555-0197",
    city: "Reston",
    state: "VA",
    timezone: "America/New_York",
    status: "DISCHARGED",
    riskLevel: "LOW",
    primaryDiagnosisCode: "F41.1",
    payerSegment: "Commercial HMO",
    referralSource: "School counselor",
    cases: [
      {
        id: "case-priya-closed",
        caseNumber: "C-23941",
        caseType: "MENTAL_HEALTH",
        programName: "Short-term anxiety stabilization",
        payerName: "Cigna LocalPlus",
        clinicalLead: "Ava Richardson, LPC",
        renderingProvider: "Synetra Counseling",
        location: "Reston clinic",
        status: "CLOSED",
        startDate: "2025-09-03",
        endDate: "2026-02-20",
        acuityLevel: "Resolved discharge goals",
        carePlanSummary:
          "Episode completed after sustained symptom reduction and family confidence with coping plan.",
        services: [
          {
            id: "service-priya-90834",
            serviceCode: "90834",
            title: "Psychotherapy, 45 minutes",
            discipline: "THERAPY",
            unitType: "VISITS",
            defaultUnitsPerSession: 1,
            defaultRateCents: 14500,
            frequency: "Biweekly during final phase",
            status: "COMPLETED",
            isPrimary: true,
            authorizations: [
              {
                id: "auth-priya-90834",
                authorizationNumber: "CGN-48011",
                payerName: "Cigna LocalPlus",
                approvedUnits: 16,
                usedUnits: 16,
                remainingUnits: 0,
                unitType: "VISITS",
                startDate: "2025-09-01",
                endDate: "2026-02-28",
                status: "EXPIRED",
                utilizationThreshold: 90,
                sessions: [
                  {
                    id: "session-priya-0218",
                    scheduledStart: "2026-02-18T16:00:00-05:00",
                    scheduledEnd: "2026-02-18T16:45:00-05:00",
                    clinicianName: "Ava Richardson",
                    clinicianTitle: "LPC",
                    location: "In-person",
                    sessionType: "Discharge session",
                    attendanceStatus: "COMPLETED",
                    unitsRendered: 1,
                    noteStatus: "LOCKED",
                    billingStatus: "PAID",
                    documentationDueAt: "2026-02-19T12:00:00-05:00",
                    progressNotes: [
                      {
                        id: "note-priya-0218",
                        authorName: "Ava Richardson",
                        status: "LOCKED",
                        submittedAt: "2026-02-18T17:01:00-05:00",
                        signedAt: "2026-02-18T17:05:00-05:00",
                        subjective:
                          "Priya and caregiver endorsed confidence in using coping ladder independently.",
                        objective:
                          "Reviewed relapse-prevention plan, school support recommendations, and discharge criteria completion.",
                        assessment:
                          "Treatment goals achieved. Clinical episode appropriate for successful discharge.",
                        plan:
                          "Discharge from episode; provide booster resources if symptoms return.",
                        incidentReported: false,
                        billingRecords: [
                          {
                            id: "billing-priya-0218",
                            claimNumber: "CLM-240218-010",
                            cptCode: "90834",
                            unitsBilled: 1,
                            amountCents: 14500,
                            status: "PAID",
                            submittedAt: "2026-02-19T09:00:00-05:00",
                            paidAt: "2026-02-26T09:30:00-05:00",
                          },
                        ],
                        complianceItems: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
