import type {
  DocumentRecord,
  FormPacketRecord,
  GroupRecord,
} from "@/lib/domain";

export const demoGroups: GroupRecord[] = [
  {
    id: "group-dbt-skills",
    name: "Teen DBT Skills Lab",
    track: "Adolescent resilience",
    serviceLine: "90853 Group psychotherapy",
    status: "ACTIVE",
    facilitatorName: "Danielle Brooks, LCSW",
    coFacilitatorName: "Alicia Monroe, PMHNP",
    location: "Telehealth",
    schedulePattern: "Mondays, 5:30 PM",
    maxCapacity: 8,
    clinicalFocus:
      "Emotion regulation, distress tolerance, and relapse prevention for teens transitioning back into school and work routines.",
    memberships: [
      {
        id: "group-dbt-member-marcus",
        clientId: "client-marcus-reed",
        caseId: "case-marcus-therapy",
        joinedAt: "2026-02-10T10:00:00-05:00",
        status: "ACTIVE",
        participationGoal:
          "Practice distress tolerance sequence before escalation at work and during trauma triggers.",
        attendanceRate: 92,
      },
      {
        id: "group-dbt-member-jordan",
        clientId: "client-jordan-ellis",
        caseId: "case-jordan-care",
        joinedAt: "2026-02-18T10:00:00-05:00",
        status: "PAUSED",
        participationGoal:
          "Build family-safe communication plan and improve conflict de-escalation.",
        attendanceRate: 68,
      },
    ],
    sessions: [
      {
        id: "group-dbt-session-0324",
        scheduledStart: "2026-03-24T17:30:00-04:00",
        scheduledEnd: "2026-03-24T18:45:00-04:00",
        facilitatorName: "Danielle Brooks, LCSW",
        location: "Telehealth",
        status: "SCHEDULED",
        noteCompletionPercent: 0,
        attendanceCount: 6,
        notesDue: 6,
      },
      {
        id: "group-dbt-session-0317",
        scheduledStart: "2026-03-17T17:30:00-04:00",
        scheduledEnd: "2026-03-17T18:45:00-04:00",
        facilitatorName: "Danielle Brooks, LCSW",
        location: "Telehealth",
        status: "COMPLETED",
        noteCompletionPercent: 83,
        attendanceCount: 5,
        notesDue: 1,
      },
    ],
  },
  {
    id: "group-social-communication",
    name: "Elementary Social Communication Club",
    track: "School readiness",
    serviceLine: "H2019 Skills training group",
    status: "ACTIVE",
    facilitatorName: "Rebekah Owens, LPC",
    coFacilitatorName: "Jocelyn Grant, QMHP",
    location: "Fairfax learning studio",
    schedulePattern: "Wednesdays, 4:00 PM",
    maxCapacity: 6,
    clinicalFocus:
      "Peer initiation, transition tolerance, and shared play routines for elementary-age members.",
    memberships: [
      {
        id: "group-social-member-naomi",
        clientId: "client-naomi-chen",
        caseId: "case-naomi-school",
        joinedAt: "2026-02-12T15:00:00-05:00",
        status: "ACTIVE",
        participationGoal:
          "Initiate peer repair after conflict and generalize cafeteria coping routine.",
        attendanceRate: 94,
      },
      {
        id: "group-social-member-elena",
        clientId: "client-elena-martinez",
        caseId: "case-elena-aba",
        joinedAt: "2026-02-20T15:00:00-05:00",
        status: "ACTIVE",
        participationGoal:
          "Increase tolerated peer-directed transitions and reduce escape-maintained cleanup refusal.",
        attendanceRate: 88,
      },
    ],
    sessions: [
      {
        id: "group-social-session-0325",
        scheduledStart: "2026-03-25T16:00:00-04:00",
        scheduledEnd: "2026-03-25T17:15:00-04:00",
        facilitatorName: "Rebekah Owens, LPC",
        location: "Fairfax learning studio",
        status: "SCHEDULED",
        noteCompletionPercent: 0,
        attendanceCount: 5,
        notesDue: 5,
      },
      {
        id: "group-social-session-0318",
        scheduledStart: "2026-03-18T16:00:00-04:00",
        scheduledEnd: "2026-03-18T17:15:00-04:00",
        facilitatorName: "Rebekah Owens, LPC",
        location: "Fairfax learning studio",
        status: "COMPLETED",
        noteCompletionPercent: 100,
        attendanceCount: 4,
        notesDue: 0,
      },
    ],
  },
  {
    id: "group-caregiver-foundations",
    name: "Caregiver Foundations Cohort",
    track: "Parent training",
    serviceLine: "97156 Caregiver-focused behavior treatment",
    status: "PLANNING",
    facilitatorName: "Sofia Nguyen, BCBA",
    location: "Hybrid",
    schedulePattern: "Fridays, 12:00 PM",
    maxCapacity: 10,
    clinicalFocus:
      "Shared caregiver training on data collection, prompting, home routines, and generalization planning.",
    memberships: [
      {
        id: "group-caregiver-member-elena",
        clientId: "client-elena-martinez",
        caseId: "case-elena-aba",
        joinedAt: "2026-03-19T11:00:00-04:00",
        status: "PENDING",
        participationGoal:
          "Build caregiver confidence with bedtime visual supports and mealtime transition routines.",
        attendanceRate: 0,
      },
    ],
    sessions: [
      {
        id: "group-caregiver-session-0327",
        scheduledStart: "2026-03-27T12:00:00-04:00",
        scheduledEnd: "2026-03-27T13:00:00-04:00",
        facilitatorName: "Sofia Nguyen, BCBA",
        location: "Hybrid",
        status: "SCHEDULED",
        noteCompletionPercent: 0,
        attendanceCount: 7,
        notesDue: 7,
      },
    ],
  },
];

export const demoDocuments: DocumentRecord[] = [
  {
    id: "doc-elena-assessment",
    clientId: "client-elena-martinez",
    caseId: "case-elena-aba",
    title: "Adaptive behavior assessment update",
    category: "ASSESSMENT",
    status: "CURRENT",
    owner: "Sofia Nguyen, BCBA",
    effectiveDate: "2026-03-08T09:00:00-04:00",
    source: "Clinical upload",
    requiresSignature: false,
    tags: ["assessment", "vineland", "aba"],
  },
  {
    id: "doc-elena-plan",
    clientId: "client-elena-martinez",
    caseId: "case-elena-aba",
    title: "Q2 treatment plan",
    category: "PLAN",
    status: "PENDING_REVIEW",
    owner: "Clinical QA",
    effectiveDate: "2026-03-15T09:00:00-04:00",
    source: "Generated from treatment planning",
    requiresSignature: true,
    tags: ["treatment-plan", "signature"],
  },
  {
    id: "doc-marcus-consent",
    clientId: "client-marcus-reed",
    caseId: "case-marcus-therapy",
    formPacketId: "form-marcus-telehealth",
    title: "Telehealth consent",
    category: "CONSENT",
    status: "EXPIRING",
    owner: "Front office",
    effectiveDate: "2025-03-30T09:00:00-04:00",
    expiresAt: "2026-03-30T23:59:00-04:00",
    source: "Client portal",
    requiresSignature: true,
    signedAt: "2025-03-30T12:12:00-04:00",
    tags: ["telehealth", "consent"],
  },
  {
    id: "doc-naomi-roi",
    clientId: "client-naomi-chen",
    caseId: "case-naomi-school",
    formPacketId: "form-naomi-roi",
    title: "School release of information",
    category: "LEGAL",
    status: "PENDING_REVIEW",
    owner: "Rebekah Owens, LPC",
    effectiveDate: "2026-03-20T09:00:00-04:00",
    source: "Secure intake packet",
    requiresSignature: true,
    tags: ["roi", "school"],
  },
  {
    id: "doc-jordan-auth",
    clientId: "client-jordan-ellis",
    caseId: "case-jordan-care",
    title: "Authorization reconsideration packet",
    category: "AUTHORIZATION",
    status: "DRAFT",
    owner: "Utilization Management",
    source: "Internal draft",
    requiresSignature: false,
    tags: ["auth", "appeal"],
  },
  {
    id: "doc-priya-discharge",
    clientId: "client-priya-patel",
    caseId: "case-priya-closed",
    title: "Discharge summary",
    category: "CLINICAL",
    status: "CURRENT",
    owner: "Ava Richardson, LPC",
    effectiveDate: "2026-02-18T17:05:00-05:00",
    source: "Locked note export",
    requiresSignature: false,
    tags: ["discharge", "clinical"],
  },
  {
    id: "doc-group-roster",
    groupId: "group-social-communication",
    title: "Social Communication Club roster and safety plan",
    category: "LEGAL",
    status: "CURRENT",
    owner: "Program operations",
    effectiveDate: "2026-03-01T08:00:00-05:00",
    source: "Program admin",
    requiresSignature: false,
    tags: ["group", "safety", "roster"],
  },
];

export const demoFormPackets: FormPacketRecord[] = [
  {
    id: "form-elena-intake-refresh",
    clientId: "client-elena-martinez",
    caseId: "case-elena-aba",
    title: "Annual intake refresh",
    packetType: "INTAKE",
    status: "IN_PROGRESS",
    assignedTo: "Family portal",
    dueDate: "2026-03-29T17:00:00-04:00",
    signatureStatus: "PARTIAL",
    completionPercent: 72,
    sections: [
      {
        id: "elena-demographics",
        title: "Demographics",
        description: "Review household and primary contact information.",
        fields: [
          { id: "preferred-name", label: "Preferred name", type: "text", value: "Elena" },
          { id: "guardian-name", label: "Guardian", type: "text", value: "Lucia Martinez" },
          { id: "phone", label: "Primary phone", type: "text", value: "(571) 555-0174" },
          { id: "language", label: "Preferred language", type: "select", value: "English / Spanish" },
        ],
      },
      {
        id: "elena-clinical",
        title: "Clinical updates",
        description: "Capture care changes since the last authorization cycle.",
        fields: [
          {
            id: "hospitalizations",
            label: "Any ER visits or hospitalizations since last review?",
            type: "textarea",
            value: "No hospitalizations. Family reported one urgent pediatric visit for seasonal respiratory illness.",
          },
          {
            id: "safety-concerns",
            label: "Current safety concerns",
            type: "textarea",
            value: "Elopement risk remains active during transitions in public settings.",
          },
        ],
      },
      {
        id: "elena-consents",
        title: "Consent acknowledgements",
        description: "Review updated privacy and treatment acknowledgements.",
        fields: [
          { id: "hipaa", label: "HIPAA acknowledgment", type: "checkbox", checked: true },
          { id: "telehealth", label: "Telehealth consent", type: "checkbox", checked: true },
          { id: "photo", label: "Photo/media release", type: "checkbox", checked: false },
        ],
      },
    ],
  },
  {
    id: "form-marcus-telehealth",
    clientId: "client-marcus-reed",
    caseId: "case-marcus-therapy",
    title: "Telehealth and financial consent renewal",
    packetType: "CONSENT",
    status: "PENDING_SIGNATURE",
    assignedTo: "Front office",
    dueDate: "2026-03-30T17:00:00-04:00",
    signatureStatus: "SENT",
    completionPercent: 88,
    sections: [
      {
        id: "marcus-telehealth",
        title: "Telehealth consent",
        description: "Confirm technology, privacy, and emergency contact expectations.",
        fields: [
          { id: "location", label: "Usual telehealth location", type: "text", value: "Home office in Richmond" },
          { id: "emergency-contact", label: "Emergency contact", type: "text", value: "Monica Reed" },
          { id: "platform", label: "Approved video platform", type: "select", value: "HIPAA Zoom" },
        ],
      },
      {
        id: "marcus-financial",
        title: "Financial responsibility",
        description: "Capture payer coordination and patient responsibility terms.",
        fields: [
          {
            id: "coordination",
            label: "Coordination of benefits update",
            type: "textarea",
            value: "Secondary coverage under review. Client uploaded updated employer benefits letter.",
          },
          { id: "payment-agreement", label: "Payment policy acknowledged", type: "checkbox", checked: true },
        ],
      },
    ],
  },
  {
    id: "form-naomi-roi",
    clientId: "client-naomi-chen",
    caseId: "case-naomi-school",
    title: "School ROI and care coordination packet",
    packetType: "ROI",
    status: "NEEDS_REVIEW",
    assignedTo: "Rebekah Owens, LPC",
    dueDate: "2026-03-26T12:00:00-04:00",
    signatureStatus: "PARTIAL",
    completionPercent: 64,
    sections: [
      {
        id: "naomi-roi-school",
        title: "School contacts",
        description: "Capture authorized recipients for two-way communication.",
        fields: [
          { id: "teacher", label: "Teacher", type: "text", value: "Ms. Hollis" },
          { id: "counselor", label: "School counselor", type: "text", value: "Tanya Miller" },
          {
            id: "scope",
            label: "Information scope",
            type: "textarea",
            value: "Attendance, behavior intervention plan implementation, and reward menu updates.",
          },
        ],
      },
      {
        id: "naomi-review",
        title: "Review flags",
        description: "Operational checks before packet is finalized.",
        fields: [
          { id: "guardian-signature", label: "Guardian signature complete", type: "checkbox", checked: true },
          { id: "school-signature", label: "School recipient acknowledged", type: "checkbox", checked: false },
        ],
      },
    ],
  },
  {
    id: "form-jordan-safety",
    clientId: "client-jordan-ellis",
    caseId: "case-jordan-care",
    title: "Safety planning and legal acknowledgements",
    packetType: "SAFETY_PLAN",
    status: "COMPLETED",
    assignedTo: "Ian Foster, QMHP",
    dueDate: "2026-03-21T12:00:00-04:00",
    completedAt: "2026-03-20T16:40:00-04:00",
    signatureStatus: "COMPLETE",
    completionPercent: 100,
    sections: [
      {
        id: "jordan-crisis",
        title: "Crisis supports",
        description: "Household de-escalation and emergency response planning.",
        fields: [
          {
            id: "warning-signs",
            label: "Early warning signs",
            type: "textarea",
            value: "Escalating verbal conflict, pacing, school refusal, and withdrawal after transportation stress.",
          },
          {
            id: "support-contacts",
            label: "Support contacts",
            type: "textarea",
            value: "Caregiver, CSB crisis line, respite coordinator, and school dean.",
          },
        ],
      },
      {
        id: "jordan-legal",
        title: "Legal acknowledgements",
        description: "Confirm privacy, emergency, and mandated reporting policies.",
        fields: [
          { id: "privacy", label: "Privacy notice reviewed", type: "checkbox", checked: true },
          { id: "mandated", label: "Mandated reporting notice reviewed", type: "checkbox", checked: true },
          { id: "emergency-policy", label: "Emergency policy reviewed", type: "checkbox", checked: true },
        ],
      },
    ],
  },
];
